#!/usr/bin/env python3
"""Convert Excalidraw's own fonts to ttf so previews use the real typefaces.

Excalidraw ships them as woff2, which CoreText cannot register, so this pulls
each one from the excalidraw repo, pins any variable axis to regular weight,
and rewrites it as ttf under Resources/Fonts with the family name the renderer
looks for. Optional: without it the renderer falls back to installed lookalikes.
"""

import io
import json
import pathlib
import sys
import urllib.request

from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

REPO = "https://api.github.com/repos/excalidraw/excalidraw/contents"
FONTS = "packages/excalidraw/fonts"
OUT = pathlib.Path(__file__).resolve().parent.parent / "Resources" / "Fonts"

# Directory in the excalidraw repo -> the family name Style.swift asks for.
FAMILIES = {
    "Excalifont": "Excalifont",
    "Nunito": "Nunito",
    "ComicShanns": "Comic Shanns",
    "Cascadia": "Cascadia Code",
    "Lilita": "Lilita One",
    "Assistant": "Assistant",
    "Virgil": "Virgil",
}


def fetch(url):
    with urllib.request.urlopen(url) as response:
        return response.read()


def rename(font, family):
    """Force the family/style names, so an axis instance named
    'Nunito ExtraLight Medium' still registers as plain 'Nunito'."""
    table = font["name"]
    for record in list(table.names):
        if record.nameID in (1, 16):
            table.setName(family, record.nameID, record.platformID,
                          record.platEncID, record.langID)
        elif record.nameID in (2, 17):
            table.setName("Regular", record.nameID, record.platformID,
                          record.platEncID, record.langID)
        elif record.nameID == 4:
            table.setName(f"{family} Regular", record.nameID, record.platformID,
                          record.platEncID, record.langID)
        elif record.nameID == 6:
            table.setName(f"{family.replace(' ', '')}-Regular", record.nameID,
                          record.platformID, record.platEncID, record.langID)


# Upstream licence, and the primary name OFL clause 3 reserves for the
# unmodified font. These files are modified (subset upstream by excalidraw,
# weight-pinned and renamed here), so a reserved name means the family cannot
# keep that name in anything redistributed. Checked against each font's own
# name table; see the "Fonts" section of the README.
LICENCES = {
    "Excalifont": ("OFL-1.1", None, "trademark of Excalidraw"),
    "Nunito": ("OFL-1.1", None, None),
    "Comic Shanns": ("MIT", None, None),
    "Cascadia Code": ("OFL-1.1", "Cascadia Code", None),
    "Lilita One": ("OFL-1.1", "Lilita", None),
    "Assistant": ("OFL-1.1", None, "inherits Reserved Font Name 'Source'"),
    "Virgil": ("OFL-1.1", None, None),
}


def write_licence_notes(converted):
    """Keep the licensing with the artefacts, not just in the README."""
    lines = [
        "# Font licences",
        "",
        "Generated by `make fonts`. These files are **not** redistributed with",
        "this repository — they are converted on your machine, from Excalidraw's",
        "own woff2 assets, for local previewing.",
        "",
        "Each file here is a *modified version*: subset upstream by Excalidraw's",
        "build (cn-font-split), then weight-pinned to 400 and renamed to its",
        "canonical family by `scripts/fetch-fonts.py` so CoreText can find it.",
        "",
        "| Family | Licence | Reserved Font Name | Copyright |",
        "| --- | --- | --- | --- |",
    ]
    for family, copyright_text in converted:
        licence, reserved, note = LICENCES.get(family, ("unknown", None, None))
        reserved = f"`{reserved}`" if reserved else "none"
        if note:
            reserved += f" ({note})"
        short = " ".join((copyright_text or "").split())[:120]
        lines += [f"| {family} | {licence} | {reserved} | {short} |"]

    lines += [
        "",
        "## Before redistributing anything built with these",
        "",
        "Private use is unrestricted: OFL 1.1 grants modification outright, and",
        "its conditions attach to redistribution. If you ship the built app, or",
        "these files, three things need doing:",
        "",
        "1. Include the full licence texts (<https://scripts.sil.org/OFL> and the",
        "   MIT notice for Comic Shanns). Excalidraw's subsetting dropped the",
        "   embedded licence records from several of these files, so the notice",
        "   no longer travels inside the font.",
        "2. Rename any family with a Reserved Font Name above — OFL clause 3",
        "   forbids a modified version using the reserved primary name, which is",
        "   exactly what the renaming step here does.",
        "3. Treat Excalifont's trademark separately from its licence.",
    ]
    (OUT / "LICENCES.md").write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT / 'LICENCES.md'}")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    converted = []
    for directory, family in FAMILIES.items():
        try:
            listing = json.loads(fetch(f"{REPO}/{FONTS}/{directory}"))
        except Exception as error:
            print(f"{family}: skipped ({error})", file=sys.stderr)
            continue

        woffs = [f for f in listing if f["name"].endswith(".woff2")]
        if not woffs:
            print(f"{family}: no woff2 found", file=sys.stderr)
            continue

        # The subsets differ only by unicode-range; the biggest covers the most.
        best = max(woffs, key=lambda f: f["size"])
        try:
            font = TTFont(io.BytesIO(fetch(best["download_url"])))
            if "fvar" in font:
                axes = {axis.axisTag: 400 for axis in font["fvar"].axes if axis.axisTag == "wght"}
                if axes:
                    font = instantiateVariableFont(font, axes, inplace=False)
            rename(font, family)
            font.flavor = None
            path = OUT / f"{family.replace(' ', '')}.ttf"
            font.save(path)
            copyright_text = font["name"].getDebugName(0)
            converted.append((family, copyright_text))
            print(f"{family}: {path.name} ({len(font.getGlyphOrder())} glyphs)")
        except Exception as error:
            print(f"{family}: conversion failed ({error})", file=sys.stderr)

    if converted:
        write_licence_notes(converted)


if __name__ == "__main__":
    main()
